[package]
name = "day-1-sum"
version = "0.1.0"
authors = ["Craig Wilkinson <craig.wilkinson@unity3d.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"